name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: patrick-kidger/action_update_python_project@v8
        with:
            python-version: "3.11"
            test-script: ""
            pypi-token: ${{ secrets.pypi_token }}
            github-user: patrick-kidger
            github-token: ${{ github.token }}
